"""
EventPilot AI — PDF Service
PDF generation for invoices and invitations using reportlab.
"""

import io
import base64
import logging
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT

logger = logging.getLogger(__name__)


def generate_invoice_pdf(
    invoice_number: str,
    event_name: str,
    vendor_name: str,
    items: list[dict],
    total: float,
    tax: float = 0,
    due_date: str = "",
) -> str:
    """
    Generate an invoice PDF and return as base64-encoded string.
    
    Returns:
        Base64-encoded PDF string (data URI format)
    """
    try:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=30*mm, bottomMargin=30*mm)
        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle('InvoiceTitle', parent=styles['Title'],
                                      fontSize=28, textColor=colors.HexColor('#4f46e5'), spaceAfter=12)
        heading_style = ParagraphStyle('InvoiceHeading', parent=styles['Heading2'],
                                        textColor=colors.HexColor('#1f2937'), fontSize=14)
        normal_style = ParagraphStyle('InvoiceNormal', parent=styles['Normal'],
                                       textColor=colors.HexColor('#374151'), fontSize=11)

        elements = []

        # Header
        elements.append(Paragraph("INVOICE", title_style))
        elements.append(Paragraph(f"#{invoice_number}", heading_style))
        elements.append(Spacer(1, 20))

        # Event and vendor info
        elements.append(Paragraph(f"<b>Event:</b> {event_name}", normal_style))
        elements.append(Paragraph(f"<b>Vendor:</b> {vendor_name}", normal_style))
        if due_date:
            elements.append(Paragraph(f"<b>Due Date:</b> {due_date}", normal_style))
        elements.append(Spacer(1, 20))

        # Items table
        table_data = [["#", "Description", "Amount"]]
        for i, item in enumerate(items, 1):
            table_data.append([
                str(i),
                item.get("description", ""),
                f"${item.get('amount', 0):,.2f}",
            ])

        # Subtotal, tax, total
        table_data.append(["", "Subtotal", f"${total - tax:,.2f}"])
        if tax > 0:
            table_data.append(["", "Tax", f"${tax:,.2f}"])
        table_data.append(["", "TOTAL", f"${total:,.2f}"])

        table = Table(table_data, colWidths=[40, 350, 100])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4f46e5')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (2, 0), (2, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('TOPPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -4), 0.5, colors.HexColor('#e5e7eb')),
            ('FONTNAME', (1, -1), (-1, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (1, -1), (-1, -1), 12),
            ('TOPPADDING', (0, -1), (-1, -1), 12),
            ('LINEABOVE', (1, -1), (-1, -1), 1.5, colors.HexColor('#4f46e5')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -4), [colors.white, colors.HexColor('#f9fafb')]),
        ]))
        elements.append(table)

        # Footer
        elements.append(Spacer(1, 40))
        footer_style = ParagraphStyle('Footer', parent=styles['Normal'],
                                       textColor=colors.HexColor('#9ca3af'), fontSize=9, alignment=TA_CENTER)
        elements.append(Paragraph("Generated by EventPilot AI • eventpilot.ai", footer_style))

        doc.build(elements)
        buffer.seek(0)
        b64 = base64.b64encode(buffer.getvalue()).decode('utf-8')
        return f"data:application/pdf;base64,{b64}"

    except Exception as e:
        logger.error(f"PDF generation error: {e}")
        return ""
